project_name: ml_pipeline_production

data:
  raw_data_path: data/raw/customer_churn.csv
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  target_column: Churn

model:
  random_state: 42
  test_size: 0.2
  model_path: artifacts/models/model.pkl

metrics:
  metrics_path: artifacts/metrics/metrics.json

mlflow:
  experiment_name: ml_pipeline_production
